/**
 * Centralized Icon component using Font Awesome (via react-icons/fa)
 */
import React from 'react'
import {
  FaRocket, FaShieldAlt, FaFlask, FaCode, FaSearch, FaBug,
  FaCubes, FaUsers, FaRobot, FaPaperPlane, FaTrash, FaCog, FaTimes,
  FaChevronDown, FaChevronRight, FaCopy, FaCheck, FaBolt, FaLightbulb,
  FaFileCode, FaTerminal, FaArrowRight, FaSpinner, FaSync, FaFolder,
  FaFolderOpen, FaFile, FaFileAlt, FaGithub, FaGlobe, FaHistory,
  FaEnvelope, FaHeart, FaStar, FaBrain, FaChartBar, FaDatabase,
  FaServer, FaCloud, FaLock, FaKey, FaUser, FaUsersCog,
  FaCogs, FaTools, FaEye, FaPlay, FaPause, FaStop,
  FaExpand, FaCompress, FaMinus, FaPlus, FaBars, FaEllipsisV,
  FaSort, FaFilter, FaCalendar, FaClock,
  FaLink, FaExternalLinkAlt, FaDownload, FaUpload,
  FaSave, FaEdit, FaStream, FaTachometerAlt,
  FaBook, FaBookmark, FaComments, FaTable, FaList,
  FaThLarge, FaPalette, FaPaintBrush,
  FaReact, FaNodeJs, FaPython, FaJs, FaHtml5, FaCss3Alt,
  FaGitAlt, FaDocker, FaLinux, FaWindows, FaApple,
  FaPlug, FaPowerOff, FaWifi, FaSignal, FaMicrochip,
  FaSitemap, FaProjectDiagram, FaNetworkWired,
  FaFlag, FaComment, FaAt, FaHashtag,
  FaRegLightbulb, FaRegCopy,
  FaArrowsAlt, FaUndo, FaRedo,
  FaMobileAlt, FaLaptop, FaDesktop, FaKeyboard, FaMouse,
  FaMemory, FaHdd, FaMap, FaCompass, FaRoute,
  FaChartLine, FaChartArea, FaChartPie,
  FaSortAmountUp, FaBalanceScale,
  FaThumbsUp, FaThumbsDown, FaBullseye, FaCrosshairs,
  FaIndustry, FaWrench, FaExchangeAlt, FaGraduationCap,
  FaDollarSign, FaHandshake, FaVectorSquare, FaBezierCurve,
  FaCircleNotch, FaListOl, FaListUl, FaTh, FaThList,
  FaBorderStyle, FaShapes, FaDraftingCompass,
  FaQuestionCircle, FaPen, FaCodeBranch, FaLayerGroup,
  FaCaretDown, FaCaretRight, FaAngleDown, FaAngleRight,
  FaImage, FaBox, FaPuzzlePiece,
  FaBell, FaExclamationTriangle, FaFont, FaGripVertical,
  FaCloudUploadAlt, FaCloudDownloadAlt, FaInfo, FaEraser, FaInfoCircle,
  FaArrowDown, FaArrowUp, FaArrowLeft, FaCheckCircle, FaChevronLeft, FaCircle, FaColumns,
  FaExclamationCircle, FaEyeSlash, FaGem, FaMicrophone, FaMoon, FaSquare,
  FaSun, FaTag, FaThermometerHalf, FaTimesCircle, FaVideo, FaUnlock,
  FaArchive, FaArrowsAltV,
  FaSignInAlt, FaSignOutAlt, FaShare,
} from 'react-icons/fa'

const ICON_MAP: Record<string, React.ComponentType<any>> = {
  'rocket': FaRocket, 'shield': FaShieldAlt, 'gauge': FaTachometerAlt,
  'flask': FaFlask, 'code': FaCode, 'search': FaSearch, 'bug': FaBug,
  'cubes': FaCubes, 'users': FaUsers, 'robot': FaRobot,
  'send': FaPaperPlane, 'trash': FaTrash, 'cog': FaCog, 'close': FaTimes,
  'chevron-down': FaChevronDown, 'chevron-right': FaChevronRight,
  'copy': FaCopy, 'check': FaCheck, 'bolt': FaBolt, 'lightbulb': FaLightbulb,
  'file-code': FaFileCode, 'terminal': FaTerminal, 'arrow-right': FaArrowRight,
  'spinner': FaSpinner, 'sync': FaSync, 'folder': FaFolder,
  'folder-open': FaFolderOpen, 'file': FaFile, 'file-alt': FaFileAlt,
  'github': FaGithub, 'globe': FaGlobe, 'envelope': FaEnvelope,
  'heart': FaHeart, 'star': FaStar, 'zap': FaBolt, 'brain': FaBrain,
  'chart-bar': FaChartBar, 'database': FaDatabase, 'server': FaServer,
  'cloud': FaCloud, 'lock': FaLock, 'key': FaKey, 'user': FaUser,
  'users-cog': FaUsersCog, 'cogs': FaCogs, 'tools': FaTools,
  'eye': FaEye, 'play': FaPlay, 'pause': FaPause, 'stop': FaStop,
  'expand': FaExpand, 'compress': FaCompress, 'minus': FaMinus,
  'plus': FaPlus, 'bars': FaBars, 'ellipsis': FaEllipsisV,
  'sort': FaSort, 'filter': FaFilter, 'calendar': FaCalendar,
  'clock': FaClock, 'link': FaLink, 'external-link': FaExternalLinkAlt,
  'download': FaDownload, 'upload': FaUpload, 'save': FaSave,
  'edit': FaEdit, 'stream': FaStream, 'tachometer': FaTachometerAlt,
  'book': FaBook, 'bookmark': FaBookmark, 'comments': FaComments,
  'table': FaTable, 'list': FaList, 'th-large': FaThLarge,
  'palette': FaPalette, 'paint-brush': FaPaintBrush,
  'react': FaReact, 'nodejs': FaNodeJs, 'python': FaPython,
  'javascript': FaJs, 'html5': FaHtml5, 'css3': FaCss3Alt,
  'git': FaGitAlt, 'docker': FaDocker, 'linux': FaLinux,
  'windows': FaWindows, 'apple': FaApple,
  'plug': FaPlug, 'power-off': FaPowerOff, 'wifi': FaWifi,
  'signal': FaSignal, 'microchip': FaMicrochip,
  'sitemap': FaSitemap, 'project-diagram': FaProjectDiagram,
  'network': FaNetworkWired, 'flag': FaFlag, 'comment': FaComment,
  'at': FaAt, 'hashtag': FaHashtag,
  'lightbulb-outline': FaRegLightbulb, 'copy-outline': FaRegCopy,
  'arrows': FaArrowsAlt, 'undo': FaUndo, 'redo': FaRedo,
  'mobile': FaMobileAlt, 'laptop': FaLaptop, 'desktop': FaDesktop,
  'keyboard': FaKeyboard, 'mouse': FaMouse, 'memory': FaMemory,
  'hdd': FaHdd, 'map': FaMap, 'compass': FaCompass, 'route': FaRoute,
  'chart-line': FaChartLine, 'chart-area': FaChartArea, 'chart-pie': FaChartPie,
  'sort-amount-up': FaSortAmountUp, 'balance-scale': FaBalanceScale,
  'thumbs-up': FaThumbsUp, 'thumbs-down': FaThumbsDown,
  'bullseye': FaBullseye, 'crosshairs': FaCrosshairs,
  'industry': FaIndustry, 'wrench': FaWrench, 'exchange': FaExchangeAlt,
  'graduation': FaGraduationCap, 'dollar': FaDollarSign,
  'handshake': FaHandshake, 'vector': FaVectorSquare, 'bezier': FaBezierCurve,
  'spinner-dots': FaCircleNotch, 'list-ordered': FaListOl,
  'border': FaBorderStyle, 'shapes': FaShapes, 'compass-alt': FaDraftingCompass,
  'question-circle': FaQuestionCircle, 'pen': FaPen, 'code-branch': FaCodeBranch,
  'layer-group': FaLayerGroup, 'caret-down': FaCaretDown, 'caret-right': FaCaretRight,
  'angle-down': FaAngleDown, 'angle-right': FaAngleRight,
  'image': FaImage, 'box': FaBox, 'puzzle': FaPuzzlePiece,
  'panel-close': FaTimes, 'bell': FaBell, 'warning': FaExclamationTriangle,
  'alert': FaExclamationTriangle,
}

interface IconProps {
  name: string
  size?: number | string
  className?: string
  color?: string
}

export default function Icon({ name, size = 16, className = '', color }: IconProps) {
  const Component = ICON_MAP[name] || FaCode
  return <Component size={size} className={className} color={color} />
}

export {
  FaRocket, FaShieldAlt, FaFlask, FaCode, FaSearch, FaBug,
  FaCubes, FaUsers, FaRobot, FaPaperPlane, FaTrash, FaCog, FaTimes,
  FaChevronDown, FaChevronRight, FaCopy, FaCheck, FaBolt, FaLightbulb,
  FaFileCode, FaTerminal, FaArrowRight, FaSpinner, FaSync, FaFolder,
  FaFolderOpen, FaFile, FaFileAlt, FaGithub, FaGlobe,
  FaEnvelope, FaHeart, FaStar, FaBrain, FaChartBar, FaDatabase,
  FaServer, FaCloud, FaLock, FaKey, FaUser, FaUsersCog,
  FaCogs, FaTools, FaEye, FaPlay, FaPause, FaStop,
  FaExpand, FaCompress, FaMinus, FaPlus, FaBars, FaEllipsisV,
  FaSort, FaFilter, FaCalendar, FaClock,
  FaLink, FaExternalLinkAlt, FaDownload, FaUpload,
  FaSave, FaEdit, FaStream, FaTachometerAlt,
  FaBook, FaBookmark, FaComments, FaTable, FaList,
  FaThLarge, FaPalette, FaPaintBrush,
  FaReact, FaNodeJs, FaPython, FaJs, FaHtml5, FaCss3Alt,
  FaGitAlt, FaDocker, FaLinux, FaWindows, FaApple,
  FaPlug, FaPowerOff, FaWifi, FaSignal, FaMicrochip,
  FaSitemap, FaProjectDiagram, FaNetworkWired,
  FaFlag, FaComment, FaAt, FaHashtag,
  FaRegLightbulb, FaRegCopy,
  FaArrowsAlt, FaUndo, FaRedo,
  FaMobileAlt, FaLaptop, FaDesktop, FaKeyboard, FaMouse,
  FaMemory, FaHdd, FaMap, FaCompass, FaRoute,
  FaChartLine, FaChartArea, FaChartPie,
  FaSortAmountUp, FaBalanceScale,
  FaThumbsUp, FaThumbsDown, FaBullseye, FaCrosshairs,
  FaIndustry, FaWrench, FaExchangeAlt, FaGraduationCap,
  FaDollarSign, FaHandshake, FaVectorSquare, FaBezierCurve,
  FaCircleNotch, FaListOl, FaListUl, FaTh, FaThList,
  FaBorderStyle, FaShapes, FaDraftingCompass,
  FaQuestionCircle, FaPen, FaCodeBranch, FaLayerGroup,
  FaCaretDown, FaCaretRight, FaAngleDown, FaAngleRight,
  FaImage, FaBox, FaPuzzlePiece,
  FaBell, FaExclamationTriangle, FaFont, FaGripVertical,
  FaCloudUploadAlt, FaCloudDownloadAlt, FaInfo, FaEraser, FaInfoCircle,
  FaArrowDown, FaArrowUp, FaArrowLeft, FaCheckCircle, FaChevronLeft, FaCircle, FaColumns,
  FaExclamationCircle, FaEyeSlash, FaGem, FaMicrophone, FaMoon, FaSquare,
  FaSun, FaTag, FaThermometerHalf, FaTimesCircle, FaVideo, FaUnlock,
  FaArchive, FaArrowsAltV, FaHistory,
  FaSignInAlt, FaSignOutAlt, FaShare,
}
