import { FALLBACK_LOCALE, type Locale } from "./protocol.js";

export const desktopMenuMessageIds = {
  file: "titleBar.menu.file",
  edit: "titleBar.menu.edit",
  view: "titleBar.menu.view",
  window: "titleBar.menu.window",
  help: "titleBar.menu.help",
  fileNewTask: "titleBar.menu.file.newTask",
  fileOpenWorkspace: "titleBar.menu.file.openWorkspace",
  fileCloseWindow: "titleBar.menu.file.closeWindow",
  editUndo: "titleBar.menu.edit.undo",
  editRedo: "titleBar.menu.edit.redo",
  editCut: "titleBar.menu.edit.cut",
  editCopy: "titleBar.menu.edit.copy",
  editPaste: "titleBar.menu.edit.paste",
  editDelete: "titleBar.menu.edit.delete",
  editSelectAll: "titleBar.menu.edit.selectAll",
  viewToggleFullScreen: "titleBar.menu.view.toggleFullScreen",
  viewActualSize: "titleBar.menu.view.actualSize",
  viewZoomIn: "titleBar.menu.view.zoomIn",
  viewZoomOut: "titleBar.menu.view.zoomOut",
  windowMinimize: "titleBar.menu.window.minimize",
  windowZoom: "titleBar.menu.window.zoom",
  windowBringAllToFront: "titleBar.menu.window.bringAllToFront",
  appServices: "titleBar.menu.app.services",
  appHide: "titleBar.menu.app.hide",
  appHideOthers: "titleBar.menu.app.hideOthers",
  appShowAll: "titleBar.menu.app.showAll",
  appQuit: "titleBar.menu.app.quit",
  helpAbout: "titleBar.menu.help.about",
  helpWhatsNew: "titleBar.menu.help.whatsNew",
  helpCheckForUpdates: "titleBar.menu.help.checkForUpdates",
  helpToggleDevTools: "titleBar.menu.help.toggleDevTools",
  helpResourceManager: "titleBar.menu.help.resourceManager",
  helpToggleIdexalStdioTap: "titleBar.menu.help.toggleIdexalStdioTap",
  helpIdexalEndpoint: "titleBar.menu.help.idexalEndpoint",
  helpIdexalEndpointProduction: "titleBar.menu.help.idexalEndpoint.production",
  helpIdexalEndpointTest: "titleBar.menu.help.idexalEndpoint.test",
  helpIdexalEndpointCustom: "titleBar.menu.help.idexalEndpoint.custom",
  helpIdexalEndpointReset: "titleBar.menu.help.idexalEndpoint.reset",
  helpFeedback: "titleBar.menu.help.feedback",
  helpExportLogs: "titleBar.menu.help.exportLogs",
  helpClearAllData: "titleBar.menu.help.clearAllData",
  helpCheckingForUpdates: "desktopMenu.help.checkingForUpdates",
  helpUpdateAvailableVersion: "desktopMenu.help.updateAvailableVersion",
  helpDownloadingUpdateVersion: "desktopMenu.help.downloadingUpdateVersion",
  helpDownloadingUpdateProgress: "desktopMenu.help.downloadingUpdateProgress",
  helpRestartToUpdate: "desktopMenu.help.restartToUpdate",
  dockShowCurrentWindow: "dock.menu.showCurrentWindow",
  trayTooltip: "tray.tooltip",
  trayOpenIdexal: "tray.menu.openIdexal",
  trayQuit: "tray.menu.quit",
} as const;

export type DesktopMenuMessageId =
  (typeof desktopMenuMessageIds)[keyof typeof desktopMenuMessageIds];

type DesktopMenuLocaleMessages = Record<DesktopMenuMessageId, string>;

export const desktopMenuMessages: Record<Locale, DesktopMenuLocaleMessages> = {
  "zh-CN": {
    "titleBar.menu.file": "文件",
    "titleBar.menu.edit": "编辑",
    "titleBar.menu.view": "视图",
    "titleBar.menu.window": "窗口",
    "titleBar.menu.help": "帮助",
    "titleBar.menu.file.newTask": "新建任务",
    "titleBar.menu.file.openWorkspace": "打开工作区",
    "titleBar.menu.file.closeWindow": "关闭窗口",
    "titleBar.menu.edit.undo": "撤销",
    "titleBar.menu.edit.redo": "重做",
    "titleBar.menu.edit.cut": "剪切",
    "titleBar.menu.edit.copy": "复制",
    "titleBar.menu.edit.paste": "粘贴",
    "titleBar.menu.edit.delete": "删除",
    "titleBar.menu.edit.selectAll": "全选",
    "titleBar.menu.view.toggleFullScreen": "切换全屏",
    "titleBar.menu.view.actualSize": "实际大小",
    "titleBar.menu.view.zoomIn": "放大",
    "titleBar.menu.view.zoomOut": "缩小",
    "titleBar.menu.window.minimize": "最小化",
    "titleBar.menu.window.zoom": "缩放",
    "titleBar.menu.window.bringAllToFront": "全部置于前台",
    "titleBar.menu.app.services": "服务",
    "titleBar.menu.app.hide": "隐藏 {appName}",
    "titleBar.menu.app.hideOthers": "隐藏其他",
    "titleBar.menu.app.showAll": "全部显示",
    "titleBar.menu.app.quit": "退出 {appName}",
    "titleBar.menu.help.about": "关于 Idexal",
    "titleBar.menu.help.whatsNew": "更新日志",
    "titleBar.menu.help.checkForUpdates": "检查更新",
    "titleBar.menu.help.toggleDevTools": "切换开发者工具",
    "titleBar.menu.help.resourceManager": "资源管理器",
    "titleBar.menu.help.toggleIdexalStdioTap": "抓取 Agent stdio 通信",
    "titleBar.menu.help.idexalEndpoint": "Idexal Endpoint",
    "titleBar.menu.help.idexalEndpoint.production": "Production（默认）",
    "titleBar.menu.help.idexalEndpoint.test": "Test",
    "titleBar.menu.help.idexalEndpoint.custom": "自定义...",
    "titleBar.menu.help.idexalEndpoint.reset": "恢复默认",
    "titleBar.menu.help.feedback": "问题上报",
    "titleBar.menu.help.exportLogs": "导出日志",
    "titleBar.menu.help.clearAllData": "清除所有数据",
    "desktopMenu.help.checkingForUpdates": "正在检查更新...",
    "desktopMenu.help.updateAvailableVersion": "发现新版本 {version}",
    "desktopMenu.help.downloadingUpdateVersion": "正在下载更新 {version}...",
    "desktopMenu.help.downloadingUpdateProgress": "正在下载更新... {progress}",
    "desktopMenu.help.restartToUpdate": "重启以更新（{version}）",
    "dock.menu.showCurrentWindow": "显示当前窗口",
    "tray.tooltip": "Idexal",
    "tray.menu.openIdexal": "打开 Idexal",
    "tray.menu.quit": "退出",
  },
  "en-US": {
    "titleBar.menu.file": "File",
    "titleBar.menu.edit": "Edit",
    "titleBar.menu.view": "View",
    "titleBar.menu.window": "Window",
    "titleBar.menu.help": "Help",
    "titleBar.menu.file.newTask": "New task",
    "titleBar.menu.file.openWorkspace": "Open workspace",
    "titleBar.menu.file.closeWindow": "Close window",
    "titleBar.menu.edit.undo": "Undo",
    "titleBar.menu.edit.redo": "Redo",
    "titleBar.menu.edit.cut": "Cut",
    "titleBar.menu.edit.copy": "Copy",
    "titleBar.menu.edit.paste": "Paste",
    "titleBar.menu.edit.delete": "Delete",
    "titleBar.menu.edit.selectAll": "Select all",
    "titleBar.menu.view.toggleFullScreen": "Toggle full screen",
    "titleBar.menu.view.actualSize": "Actual size",
    "titleBar.menu.view.zoomIn": "Zoom in",
    "titleBar.menu.view.zoomOut": "Zoom out",
    "titleBar.menu.window.minimize": "Minimize",
    "titleBar.menu.window.zoom": "Zoom",
    "titleBar.menu.window.bringAllToFront": "Bring all to front",
    "titleBar.menu.app.services": "Services",
    "titleBar.menu.app.hide": "Hide {appName}",
    "titleBar.menu.app.hideOthers": "Hide others",
    "titleBar.menu.app.showAll": "Show all",
    "titleBar.menu.app.quit": "Quit {appName}",
    "titleBar.menu.help.about": "About Idexal",
    "titleBar.menu.help.whatsNew": "What's new",
    "titleBar.menu.help.checkForUpdates": "Check for updates",
    "titleBar.menu.help.toggleDevTools": "Toggle developer tools",
    "titleBar.menu.help.resourceManager": "Resource manager",
    "titleBar.menu.help.toggleIdexalStdioTap": "Capture agent stdio traffic",
    "titleBar.menu.help.idexalEndpoint": "Idexal Endpoint",
    "titleBar.menu.help.idexalEndpoint.production": "Production (default)",
    "titleBar.menu.help.idexalEndpoint.test": "Test",
    "titleBar.menu.help.idexalEndpoint.custom": "Custom...",
    "titleBar.menu.help.idexalEndpoint.reset": "Reset to default",
    "titleBar.menu.help.feedback": "Feedback",
    "titleBar.menu.help.exportLogs": "Export logs",
    "titleBar.menu.help.clearAllData": "Clear all data",
    "desktopMenu.help.checkingForUpdates": "Checking for updates...",
    "desktopMenu.help.updateAvailableVersion": "Update available {version}",
    "desktopMenu.help.downloadingUpdateVersion": "Downloading update {version}...",
    "desktopMenu.help.downloadingUpdateProgress": "Downloading update... {progress}",
    "desktopMenu.help.restartToUpdate": "Restart to update ({version})",
    "dock.menu.showCurrentWindow": "Show current window",
    "tray.tooltip": "Idexal",
    "tray.menu.openIdexal": "Open Idexal",
    "tray.menu.quit": "Quit",
  },
  ar: {
    "titleBar.menu.file": "ملف",
    "titleBar.menu.edit": "تحرير",
    "titleBar.menu.view": "عرض",
    "titleBar.menu.window": "نافذة",
    "titleBar.menu.help": "مساعدة",
    "titleBar.menu.file.newTask": "مهمة جديدة",
    "titleBar.menu.file.openWorkspace": "فتح مساحة عمل",
    "titleBar.menu.file.closeWindow": "إغلاق النافذة",
    "titleBar.menu.edit.undo": "تراجع",
    "titleBar.menu.edit.redo": "إعادة",
    "titleBar.menu.edit.cut": "قص",
    "titleBar.menu.edit.copy": "نسخ",
    "titleBar.menu.edit.paste": "لصق",
    "titleBar.menu.edit.delete": "حذف",
    "titleBar.menu.edit.selectAll": "تحديد الكل",
    "titleBar.menu.view.toggleFullScreen": "ملء الشاشة",
    "titleBar.menu.view.actualSize": "الحجم الفعلي",
    "titleBar.menu.view.zoomIn": "تكبير",
    "titleBar.menu.view.zoomOut": "تصغير",
    "titleBar.menu.window.minimize": "تصغير",
    "titleBar.menu.window.zoom": "تكبير/تصغير",
    "titleBar.menu.window.bringAllToFront": "جلب الكل للمقدمة",
    "titleBar.menu.app.services": "خدمات",
    "titleBar.menu.app.hide": "إخفاء {appName}",
    "titleBar.menu.app.hideOthers": "إخفاء الآخرين",
    "titleBar.menu.app.showAll": "إظهار الكل",
    "titleBar.menu.app.quit": "إنهاء {appName}",
    "titleBar.menu.help.about": "حول Idexal",
    "titleBar.menu.help.whatsNew": "سجل التحديثات",
    "titleBar.menu.help.checkForUpdates": "التحقق من التحديثات",
    "titleBar.menu.help.toggleDevTools": "أدوات المطورين",
    "titleBar.menu.help.resourceManager": "مدير الموارد",
    "titleBar.menu.help.toggleIdexalStdioTap": "التقاط اتصال stdio للوكيل",
    "titleBar.menu.help.idexalEndpoint": "نقطة نهاية Idexal",
    "titleBar.menu.help.idexalEndpoint.production": "الإنتاج (افتراضي)",
    "titleBar.menu.help.idexalEndpoint.test": "اختبار",
    "titleBar.menu.help.idexalEndpoint.custom": "مخصص...",
    "titleBar.menu.help.idexalEndpoint.reset": "استعادة الافتراضي",
    "titleBar.menu.help.feedback": "إبلاغ عن مشكلة",
    "titleBar.menu.help.exportLogs": "تصدير السجلات",
    "titleBar.menu.help.clearAllData": "مسح كل البيانات",
    "desktopMenu.help.checkingForUpdates": "جارٍ التحقق من التحديثات...",
    "desktopMenu.help.updateAvailableVersion": "تحديث جديد {version}",
    "desktopMenu.help.downloadingUpdateVersion": "جارٍ تنزيل التحديث {version}...",
    "desktopMenu.help.downloadingUpdateProgress": "جارٍ تنزيل التحديث... {progress}",
    "desktopMenu.help.restartToUpdate": "أعد التشغيل للتحديث ({version})",
    "dock.menu.showCurrentWindow": "إظهار النافذة الحالية",
    "tray.tooltip": "Idexal",
    "tray.menu.openIdexal": "فتح Idexal",
    "tray.menu.quit": "إنهاء",
  },
  fr: {
    "titleBar.menu.file": "Fichier",
    "titleBar.menu.edit": "Édition",
    "titleBar.menu.view": "Affichage",
    "titleBar.menu.window": "Fenêtre",
    "titleBar.menu.help": "Aide",
    "titleBar.menu.file.newTask": "Nouvelle tâche",
    "titleBar.menu.file.openWorkspace": "Ouvrir un espace de travail",
    "titleBar.menu.file.closeWindow": "Fermer la fenêtre",
    "titleBar.menu.edit.undo": "Annuler",
    "titleBar.menu.edit.redo": "Rétablir",
    "titleBar.menu.edit.cut": "Couper",
    "titleBar.menu.edit.copy": "Copier",
    "titleBar.menu.edit.paste": "Coller",
    "titleBar.menu.edit.delete": "Supprimer",
    "titleBar.menu.edit.selectAll": "Tout sélectionner",
    "titleBar.menu.view.toggleFullScreen": "Plein écran",
    "titleBar.menu.view.actualSize": "Taille réelle",
    "titleBar.menu.view.zoomIn": "Agrandir",
    "titleBar.menu.view.zoomOut": "Réduire",
    "titleBar.menu.window.minimize": "Réduire",
    "titleBar.menu.window.zoom": "Zoom",
    "titleBar.menu.window.bringAllToFront": "Tout ramener au premier plan",
    "titleBar.menu.app.services": "Services",
    "titleBar.menu.app.hide": "Masquer {appName}",
    "titleBar.menu.app.hideOthers": "Masquer les autres",
    "titleBar.menu.app.showAll": "Tout afficher",
    "titleBar.menu.app.quit": "Quitter {appName}",
    "titleBar.menu.help.about": "À propos d'Idexal",
    "titleBar.menu.help.whatsNew": "Notes de version",
    "titleBar.menu.help.checkForUpdates": "Rechercher des mises à jour",
    "titleBar.menu.help.toggleDevTools": "Outils de développement",
    "titleBar.menu.help.resourceManager": "Gestionnaire de ressources",
    "titleBar.menu.help.toggleIdexalStdioTap": "Capturer le stdio de l'agent",
    "titleBar.menu.help.idexalEndpoint": "Point de terminaison Idexal",
    "titleBar.menu.help.idexalEndpoint.production": "Production (par défaut)",
    "titleBar.menu.help.idexalEndpoint.test": "Test",
    "titleBar.menu.help.idexalEndpoint.custom": "Personnalisé...",
    "titleBar.menu.help.idexalEndpoint.reset": "Rétablir par défaut",
    "titleBar.menu.help.feedback": "Signaler un problème",
    "titleBar.menu.help.exportLogs": "Exporter les journaux",
    "titleBar.menu.help.clearAllData": "Effacer toutes les données",
    "desktopMenu.help.checkingForUpdates": "Recherche de mises à jour...",
    "desktopMenu.help.updateAvailableVersion": "Nouvelle version {version}",
    "desktopMenu.help.downloadingUpdateVersion": "Téléchargement de la mise à jour {version}...",
    "desktopMenu.help.downloadingUpdateProgress": "Téléchargement... {progress}",
    "desktopMenu.help.restartToUpdate": "Redémarrer pour mettre à jour ({version})",
    "dock.menu.showCurrentWindow": "Afficher la fenêtre actuelle",
    "tray.tooltip": "Idexal",
    "tray.menu.openIdexal": "Ouvrir Idexal",
    "tray.menu.quit": "Quitter",
  },
};

export function getDesktopMenuMessage(locale: Locale, id: DesktopMenuMessageId): string {
  // 回退语言必须是英文：DEFAULT_LOCALE 目前是 zh-CN，用它兜底会让阿语/法语用户看到中文菜单。
  const messages = desktopMenuMessages[locale] ?? desktopMenuMessages[FALLBACK_LOCALE];
  return messages[id];
}

export function formatDesktopMenuMessage(
  locale: Locale,
  id: DesktopMenuMessageId,
  values?: Record<string, string | number>,
): string {
  let message = getDesktopMenuMessage(locale, id);
  if (!values) {
    return message;
  }

  for (const [key, value] of Object.entries(values)) {
    message = message.replaceAll(`{${key}}`, String(value));
  }

  return message;
}
